package com.cognis.app.web.utils;

public enum ErrorCode {
    
	VARIFICATION_FAILED("VARIFICATION_FAILED"),
    USER_ALREADY_EXIST("USER_ALREADY_EXIST"),
	USER_NOT_FOUND("USER_NOT_FOUND"),  
	ADDRESS_NOT_AVAILABLE("ADDRESS_NOT_AVAILABLE"),
	INVALID_TOKEN("INVALID_TOKEN"),
	CUSTOMER_DETAILS_ALREADY_EXIST("CUSTOMER_DETAILS_ALREADY_EXIST_FOR_THIS_LOGIN_USER"),
	VENDOR_DETAILS_ALREADY_EXIST("VENDOR_DETAILS_ALREADY_EXIST_FOR_THIS_LOGIN_USER"),
	SERVICE_PROVIDER_DETAILS_ALREADY_EXIST("SERVICE_PROVIDER_DETAILS_ALREADY_EXIST_FOR_THIS_LOGIN_USER"),
	ADDRESS_DETAILS_ALREADY_EXIST("ADDRESS_ALREADY_EXIST_FOR_THIS_LOGIN_USER"),
	SERVICE_ALREADY_EXIST("SERVICE_ALREADY_EXIST");
	
	
    String errorCode;
    
    ErrorCode(String errorCode){
      this.errorCode=  errorCode;
     
    }
    
    public String getErrorCode(){
        return errorCode;
    }
    public static final int SC_APPLICATION_ERROR = 400;
    //TODO NEED TO DEFINE SERVER ERROR
    public static final int SC_SERVER_ERROR=500;
	public static final int SC_OK = 200;
	public static final String FAILED = "FAILED"; 
	public static final String SC_LOGIN_ERROR="SALOON_ERROR_100000";
}
