/**
 * 
 */
package com.cognis.app.web.utils;

/**
 * @author Siddharth
 *
 */
public enum SuccessCode {


	SUCCESSFULLY_LOGIN_MSG("SUCCESSFULLY_LOGIN"),
	SUCCESSFULLY_ADDED_MSG("SUCCESSFULLY_ADDED"),
	SUCCESSFULLY_VALIDTAE_MSG("SUCCESSFULLY_VALITAE"),
	SUCCESSFULLY_GET_ADDRESSS_MSG("SUCCESSFULLY_GET_ADDRESSS"),
	SUCCESSFULLY_GET_CUSTOMER_MSG("SUCCESSFULLY_GET_CUSTOMER_DTLS"),
	SUCCESSFULLY_GET_SERVICE_PROVIDER_MSG("SUCCESSFULLY_GET_SERVICE_PROVIDER_DTLS"),
	SUCCESSFULLY_GET_VENDOR_MSG("SUCCESSFULLY_GET_VENDOR_DTLS"),
	SUCCESSFULLY_UPDATED_MSG("SUCCESSFULLY_UPDATED"),
	SUCCESSFULLY_ADD_SALOON_SERVICE("SUCCESSFULLY_ADD_SALOON_SERVICE"),
	SUCCESSFULLY_ADD_MANU("SUCCESSFULLY_ADD_MANU"),
	SUCCESSFULLY_GET_LIST_OF_SALOON_SERVICES("SUCCESSFULLY_GET_LIST_OF_SALOON_SERVICES"),
	SUCCESSFULLY_DELETE_SALOON_SERVICE("SUCCESSFULLY_DELETE_SALOON_SERVICE"),
	SUCCESSFULLY_ADD_MANU_ITEAM("SUCCESSFULLY_ADD_MANU_ITEAM"),
	SUCCESSFULLY_ADD_BOOKING("BOOGING_CONFIRM"),
	SUCCESSFULLY_GET_BOOKIG_SLOT("SUCCESSFULLY_GET_BOOKIG_SLOT"),
	SUCCESSFULLY_GET_LIST_OF_SERVICES_AND_VENDOR_PROVIDER("SUCCESSFULLY_GET_SERVICES_AND_VENDOR_PROVIDER"),
	SUCCESSFULLY_GET_SERVICES_PROVIDER("SUCCESSFULLY_GET_SERVICES_DETAILES"),
	SUCCESSFULLY_GET_FREELANCE_VENDOR("SUCCESSFULLY_GET_FREELANCE_VENDOR_DETAILES");
	
    String successCode;

	  SuccessCode(String successCode) {
		this.successCode=successCode;
	}

	public String getSuccessCode() {
		return successCode;
	}
	

	public static final int SC_OK = 200;
	public static final String SUCCESS = "TRUE"; 
	
}
