CREATE DATABASE SALOON_SCHEMA;

USE SALOON_SCHEMA;



DROP TABLE ROLE;
 CREATE TABLE ROLE(
  ROLE_ID INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT, 
  PRIMARY KEY (ROLE_ID), 
  ROLE_NAME VARCHAR(50)NOT NULL,
  REMARKS VARCHAR(100)
   );
   
   DROP TABLE SALOONE_SERVICE_PROVIDER;
   DROP TABLE FREELANCE_VENDOR;
   DROP TABLE ADDRESS_INFO;  

  CREATE TABLE ADDRESS_INFO(
       ADDRESS_ID INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
       PRIMARY KEY (ADDRESS_ID),
       ADDRESS1 VARCHAR(100)NOT NULL,
       ADDRESS2 VARCHAR(100),
       LATTITUDE DOUBLE,
       LONGITUDE DOUBLE,
       CITY VARCHAR(50),
	   DISTRICT VARCHAR(50),
       STATE VARCHAR(20),
       PIN_CODE VARCHAR(6),
       LOCATION VARCHAR(50)
       );

CREATE TABLE SALOONE_SERVICE_PROVIDER(
  SERVICE_ID INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT, 
  PRIMARY KEY (SERVICE_ID), 
  SERVICE_NAME VARCHAR(20)NOT NULL,
  ADDRESS_ID_FK INT(5) UNSIGNED, FOREIGN KEY (ADDRESS_ID_FK) REFERENCES  ADDRESS_INFO(ADDRESS_ID),
  ROLE_ID_FK INT(5) UNSIGNED, FOREIGN KEY (ROLE_ID_FK) REFERENCES  ROLE(ROLE_ID),
  PHONE VARCHAR(10), 
  PAN_NO VARCHAR(20), 
  REGISISTRATION_ID INT(10),
  OTHER_CARD_NO VARCHAR(10), 
  EMAIL VARCHAR(50)NOT NULL,
  PASSWORD VARCHAR(100)NOT NULL,
  LOCATION VARCHAR(100),
  STATUS VARCHAR(100)
   );
   

CREATE TABLE FREELANCE_VENDOR(
  VENDOR_ID INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT, 
  PRIMARY KEY (VENDOR_ID), 
  VENDOR_NAME VARCHAR(20)NOT NULL,
  ROLE_ID_FK INT(5) UNSIGNED, FOREIGN KEY (ROLE_ID_FK) REFERENCES  ROLE(ROLE_ID),
  ADDRESS_ID_FK INT(5) UNSIGNED, FOREIGN KEY (ADDRESS_ID_FK) REFERENCES  ADDRESS_INFO(ADDRESS_ID),
  PHONE VARCHAR(10),
  PAN_NO VARCHAR(20), 
  OTHER_CARD_NO VARCHAR(10), 
  EMAIL VARCHAR(50)NOT NULL, 
  PASSWORD VARCHAR(100)NOT NULL
   );
   


 