create database saloon;
use saloon;

drop table ACC_VERIFICATION_TOKEN;
drop table CUSTOMER_INFO;
drop table ADDRESS_INFO;
drop table FREELANCE_VENDOR;
drop table SERVICE_PROVIDER;
drop table MANU_TABLE;
drop table USER_INFO;
drop table ROLE_INFO;
drop table SERVICE;

CREATE TABLE ROLE_INFO (
    ROLE_ID INT(15) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ROLE_TYPE varchar(100) NOT NULL,
	ROLE_VALUE INT,
	REMARK varchar(4000)
);
insert into ROLE_INFO(ROLE_TYPE,ROLE_VALUE,REMARK) values('Sevice Provider(saloon)',1,'saloon sorcvice provider');
insert into ROLE_INFO(ROLE_TYPE,ROLE_VALUE,REMARK) values('Freelance',2,'i am here to give best version for yourshelf ');
insert into ROLE_INFO(ROLE_TYPE,ROLE_VALUE,REMARK) values('End User',0,'receive sorcvice from saloon');
insert into ROLE_INFO(ROLE_TYPE,REMARK) values('Admin','saloon chairman');


CREATE TABLE SERVICE(
SERVICE_ID INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
SERVICE_NAME VARCHAR(50) NOT NULL UNIQUE,
SERVICE_STATUS VARCHAR(1) DEFAULT 'A',
DESCRIPTION VARCHAR(100),
IMAGEURL VARCHAR(200)
);



CREATE TABLE USER_INFO (
    USER_ID INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(50) NOT NULL,
	PHONE_NO VARCHAR(10) NOT NULL ,
    ROLE_VALUE INT(5) ,
	EMIL_ID VARCHAR(100)  NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	VERIFICATION_STATUS VARCHAR(1)  DEFAULT 'N',
	ACTIVE_IN_STATUS VARCHAR(1) DEFAULT 'A',  
	CREATE_BY VARCHAR(50),
	UPDATE_BY VARCHAR(50),
	CREATEDDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATEDDATE DATETIME ,
    LAST_LOGIN_TIME DATETIME ,
	LOGIN_TOKEN VARCHAR(20) , 
	UNIQUE(PHONE_NO)	
);


CREATE TABLE ACC_VERIFICATION_TOKEN(
TOKEN_ID INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
TOKEN_NUMBER VARCHAR(6),
USER_FK INT,
FOREIGN KEY (USER_FK) REFERENCES USER_INFO(USER_ID)
);

CREATE TABLE ADDRESS_INFO(
ADDRESS_PK INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
ADDRESS_1 VARCHAR(1000) NOT NULL,
ADDRESS_2 VARCHAR(1000),
STATE VARCHAR(50),
DISTRICT VARCHAR(100),
CITY VARCHAR(100),
POSTAL_CODE VARCHAR(6) NOT NULL,
LATITUDE DOUBLE,
LONGITUDE DOUBLE,
USER_FK INT NOT NULL UNIQUE,
FOREIGN KEY (USER_FK) REFERENCES USER_INFO(USER_ID),
CREATE_BY VARCHAR(100),
UPDATE_BY VARCHAR(100),
CREATEDDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
UPDATEDDATE DATETIME 
);

CREATE TABLE CUSTOMER_INFO (
    CUSTOMER_ID INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_FK INT NOT NULL UNIQUE,
	FOREIGN KEY (USER_FK) REFERENCES USER_INFO(USER_ID)		
);


CREATE TABLE FREELANCE_VENDOR(
VENDOR_ID INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
PAN_NO VARCHAR(20),
OTHER_CARD_NO VARCHAR(10),
SEATING_CAPACITY VARCHAR(50) DEFAULT '1',
USER_FK INT(5) NOT NULL UNIQUE,
FOREIGN KEY (USER_FK) REFERENCES USER_INFO(USER_ID)
);

CREATE TABLE SERVICE_PROVIDER(
SERVICE_PROVIDER_ID INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
GST_NUMBER VARCHAR(20),
BUSINESS_REGISISTRATION_ID VARCHAR(10),
SEATING_CAPACITY VARCHAR(50),
USER_FK INT(5) NOT NULL UNIQUE,
FOREIGN KEY (USER_FK) REFERENCES USER_INFO(USER_ID)
);


CREATE TABLE MANU_TABLE(
MANU_ID INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
USER_FK INT  ,
SERVICE_FK INT  ,
FOREIGN KEY (USER_FK) REFERENCES USER_INFO(USER_ID),
FOREIGN KEY (SERVICE_FK) REFERENCES SERVICE(SERVICE_ID),
PRICE VARCHAR(10),
DESCRIPTION VARCHAR(200),
ACTIVE_IN_STATUS VARCHAR(1) DEFAULT 'A'
);